name: "My action"
description: "Test my action"

inputs:
  message:
    description: "Enter a message"
    required: true
    default: "Mundo"

runs:
  using: "composite"

  steps:
    - name: Hola mundo
      run: echo "Hola ${{inputs.message}}"
      shell: bash
