name: "Ejemplo de Composite action"

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    env:
      USER_NAME: Elias iabñez

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Variable entorno jobs
        run: echo "Variable entorno en Jobs ${{USER_NAME}}"

      - name: variable entorno GITHUB
        run: echo "Variable entorno en GITHUB ${{vars.USER_NAME}}"