name: Test

on: [push]

jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: LS
        run:  |
          chmod +x script.sh
          ./script.sh