name: Hola mundo

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Hola mundo
      run: echo "Hola mundo"

    - name: Touch file
      run: touch hola.txt

    - name: Set text
      run: echo "Hola mundo" > hola.txt

    - name: Read file
      run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: LS
        run: ls -al

      - name: My action"
        uses: ./.github/actions/my-action